version: '3'
services:
  tweepy:
    build: .
    container_name: "tweepy"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - /home/ubuntu/twitter_feed/code:/code
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    restart: always
