version: '3'
services:
  tweepy:
    build: .
    container_name: "tweepy"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - /home/ubuntu/twitter_feed/data:/data
      - /home/ubuntu/twitter_feed/code:/code
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /srv/docker/mongodb:/var/lib/mongodb
    restart: always
